import {
  Airplane01Icon,
  AnalyticsUpIcon,
  Atm01Icon,
  Baby01Icon,
  BabyBottleIcon,
  Backpack01Icon,
  BandageIcon,
  BankIcon,
  BarcodeScanIcon,
  Basketball01Icon,
  BeachIcon,
  Bicycle01Icon,
  BirdIcon,
  BirthdayCakeIcon,
  BitcoinIcon,
  BoatIcon,
  Bone01Icon,
  Book01Icon,
  Bread01Icon,
  Briefcase01Icon,
  BulbIcon,
  Bus01Icon,
  Camera01Icon,
  CamperIcon,
  CampfireIcon,
  Car01Icon,
  CashbackIcon,
  Cash01Icon,
  ChartBarLineIcon,
  ChartUpIcon,
  CharityIcon,
  ChefHatIcon,
  ClothesIcon,
  Coffee01Icon,
  Coins01Icon,
  CompassIcon,
  ComputerIcon,
  Coupon01Icon,
  CreditCardIcon,
  DentalToothIcon,
  DiceIcon,
  DiscountTag01Icon,
  Doctor01Icon,
  DrinkIcon,
  Dumbbell01Icon,
  ElectricHome01Icon,
  EvChargingIcon,
  Film01Icon,
  FirstAidKitIcon,
  FlowerPotIcon,
  FootballIcon,
  Fuel01Icon,
  GameController01Icon,
  GasStoveIcon,
  GiftIcon,
  GlassesIcon,
  GlobeIcon,
  GraduationScrollIcon,
  HairDryerIcon,
  Hamburger01Icon,
  HeadphonesIcon,
  HeartCheckIcon,
  HelicopterIcon,
  Home01Icon,
  Hospital01Icon,
  Hotel01Icon,
  IceCream01Icon,
  InternetIcon,
  Invoice01Icon,
  JobSearchIcon,
  KidIcon,
  Leaf01Icon,
  LoyaltyCardIcon,
  Luggage01Icon,
  MapPinIcon,
  Medicine01Icon,
  MetroIcon,
  Mic01Icon,
  MoneyBag01Icon,
  Motorbike01Icon,
  MountainIcon,
  MusicNote01Icon,
  NoodlesIcon,
  ParkingMeterIcon,
  PartyIcon,
  Passport01Icon,
  PerfumeIcon,
  PetrolPumpIcon,
  PiggyBankIcon,
  PillIcon,
  Pizza01Icon,
  PopcornIcon,
  PowerIcon,
  ProfitIcon,
  Pulse01Icon,
  ReceiptTextIcon,
  Restaurant01Icon,
  Router01Icon,
  RunningShoesIcon,
  SafeBoxIcon,
  SavingsIcon,
  School01Icon,
  SchoolBusIcon,
  Scooter01Icon,
  Shirt01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SodaCanIcon,
  SolarEnergyIcon,
  SteakIcon,
  Stethoscope02Icon,
  SunglassesIcon,
  SurfboardIcon,
  Sushi01Icon,
  SwimmingCapIcon,
  Tag01Icon,
  Tap01Icon,
  TaxesIcon,
  Taxi02Icon,
  TeaIcon,
  TennisBallIcon,
  TentIcon,
  TheaterIcon,
  Ticket01Icon,
  TipsIcon,
  ToolboxIcon,
  ToyBrickIcon,
  TradeDownIcon,
  TradeUpIcon,
  Train01Icon,
  TravelBagIcon,
  TruckIcon,
  VaccineIcon,
  VolleyballIcon,
  VoucherIcon,
  Wallet02Icon,
  WashingMachineIcon,
  WaterPumpIcon,
  Wifi01Icon,
  WorkoutRunIcon,
  Wrench01Icon,
  Yoga01Icon,
} from '@hugeicons/core-free-icons'
import type { HugeiconsIconProps } from '@hugeicons/react'

type HugeIcon = HugeiconsIconProps['icon']

export const ICON_MAP: Record<string, HugeIcon> = {
  'wallet-02': Wallet02Icon,
  bank: BankIcon,
  'credit-card': CreditCardIcon,
  'money-bag-01': MoneyBag01Icon,
  'piggy-bank': PiggyBankIcon,
  'cash-01': Cash01Icon,
  coin: Coins01Icon,
  'chart-bar-01': ChartBarLineIcon,
  savings: SavingsIcon,
  'home-01': Home01Icon,
  'shopping-bag-01': ShoppingBag01Icon,
  'shopping-cart-01': ShoppingCart01Icon,
  'car-01': Car01Icon,
  'airplane-01': Airplane01Icon,
  'restaurant-01': Restaurant01Icon,
  'coffee-01': Coffee01Icon,
  'pizza-01': Pizza01Icon,
  'hamburger-01': Hamburger01Icon,
  'bus-01': Bus01Icon,
  'taxi-02': Taxi02Icon,
  'train-01': Train01Icon,
  'fuel-01': Fuel01Icon,
  'petrol-pump': PetrolPumpIcon,
  'heart-check': HeartCheckIcon,
  'pulse-01': Pulse01Icon,
  'stethoscope-02': Stethoscope02Icon,
  'medicine-01': Medicine01Icon,
  'hospital-01': Hospital01Icon,
  'book-01': Book01Icon,
  'school-01': School01Icon,
  'graduation-scroll': GraduationScrollIcon,
  'game-controller-01': GameController01Icon,
  'music-note-01': MusicNote01Icon,
  'film-01': Film01Icon,
  'dumbbell-01': Dumbbell01Icon,
  'smart-phone-01': SmartPhone01Icon,
  internet: InternetIcon,
  clothes: ClothesIcon,
  'shirt-01': Shirt01Icon,
  gift: GiftIcon,
  'hotel-01': Hotel01Icon,
  'briefcase-01': Briefcase01Icon,
  'job-search': JobSearchIcon,
  'invoice-01': Invoice01Icon,
  computer: ComputerIcon,
  'ice-cream-01': IceCream01Icon,
  tea: TeaIcon,
  'birthday-cake': BirthdayCakeIcon,
  steak: SteakIcon,
  'sushi-01': Sushi01Icon,
  noodles: NoodlesIcon,
  'bread-01': Bread01Icon,
  'soda-can': SodaCanIcon,
  drink: DrinkIcon,
  'chef-hat': ChefHatIcon,
  'bicycle-01': Bicycle01Icon,
  'motorbike-01': Motorbike01Icon,
  'scooter-01': Scooter01Icon,
  truck: TruckIcon,
  boat: BoatIcon,
  metro: MetroIcon,
  'parking-meter': ParkingMeterIcon,
  'ev-charging': EvChargingIcon,
  helicopter: HelicopterIcon,
  'tap-01': Tap01Icon,
  'water-pump': WaterPumpIcon,
  power: PowerIcon,
  'electric-home-01': ElectricHome01Icon,
  'solar-energy': SolarEnergyIcon,
  'wifi-01': Wifi01Icon,
  'router-01': Router01Icon,
  'gas-stove': GasStoveIcon,
  'washing-machine': WashingMachineIcon,
  bulb: BulbIcon,
  toolbox: ToolboxIcon,
  'wrench-01': Wrench01Icon,
  'flower-pot': FlowerPotIcon,
  'leaf-01': Leaf01Icon,
  'doctor-01': Doctor01Icon,
  'dental-tooth': DentalToothIcon,
  bandage: BandageIcon,
  'first-aid-kit': FirstAidKitIcon,
  vaccine: VaccineIcon,
  pill: PillIcon,
  'hair-dryer': HairDryerIcon,
  perfume: PerfumeIcon,
  glasses: GlassesIcon,
  sunglasses: SunglassesIcon,
  football: FootballIcon,
  'basketball-01': Basketball01Icon,
  'tennis-ball': TennisBallIcon,
  volleyball: VolleyballIcon,
  'yoga-01': Yoga01Icon,
  'workout-run': WorkoutRunIcon,
  'running-shoes': RunningShoesIcon,
  'swimming-cap': SwimmingCapIcon,
  surfboard: SurfboardIcon,
  'camera-01': Camera01Icon,
  party: PartyIcon,
  theater: TheaterIcon,
  'ticket-01': Ticket01Icon,
  popcorn: PopcornIcon,
  dice: DiceIcon,
  headphones: HeadphonesIcon,
  'mic-01': Mic01Icon,
  'baby-01': Baby01Icon,
  'baby-bottle': BabyBottleIcon,
  kid: KidIcon,
  'toy-brick': ToyBrickIcon,
  'school-bus': SchoolBusIcon,
  'backpack-01': Backpack01Icon,
  bird: BirdIcon,
  'bone-01': Bone01Icon,
  'discount-tag-01': DiscountTag01Icon,
  'coupon-01': Coupon01Icon,
  voucher: VoucherIcon,
  'barcode-scan': BarcodeScanIcon,
  'loyalty-card': LoyaltyCardIcon,
  'tag-01': Tag01Icon,
  'analytics-up': AnalyticsUpIcon,
  'chart-up': ChartUpIcon,
  'trade-up': TradeUpIcon,
  'trade-down': TradeDownIcon,
  bitcoin: BitcoinIcon,
  'safe-box': SafeBoxIcon,
  'atm-01': Atm01Icon,
  'receipt-text': ReceiptTextIcon,
  cashback: CashbackIcon,
  profit: ProfitIcon,
  tips: TipsIcon,
  taxes: TaxesIcon,
  charity: CharityIcon,
  'luggage-01': Luggage01Icon,
  'travel-bag': TravelBagIcon,
  'passport-01': Passport01Icon,
  tent: TentIcon,
  compass: CompassIcon,
  'map-pin': MapPinIcon,
  beach: BeachIcon,
  mountain: MountainIcon,
  camper: CamperIcon,
  globe: GlobeIcon,
  campfire: CampfireIcon,
}

export const getIconByName = (name: string): HugeIcon =>
  ICON_MAP[name] ?? Wallet02Icon

export const ACCOUNT_ICON_NAMES = [
  'wallet-02',
  'bank',
  'credit-card',
  'money-bag-01',
  'piggy-bank',
  'cash-01',
  'coin',
  'chart-bar-01',
  'savings',
]

export const CATEGORY_ICON_NAMES = [
  'restaurant-01',
  'coffee-01',
  'pizza-01',
  'hamburger-01',
  'ice-cream-01',
  'tea',
  'birthday-cake',
  'steak',
  'sushi-01',
  'noodles',
  'bread-01',
  'soda-can',
  'drink',
  'chef-hat',
  'shopping-cart-01',
  'shopping-bag-01',
  'discount-tag-01',
  'coupon-01',
  'voucher',
  'barcode-scan',
  'loyalty-card',
  'tag-01',
  'clothes',
  'shirt-01',
  'gift',
  'home-01',
  'tap-01',
  'water-pump',
  'power',
  'electric-home-01',
  'solar-energy',
  'wifi-01',
  'router-01',
  'gas-stove',
  'washing-machine',
  'bulb',
  'toolbox',
  'wrench-01',
  'flower-pot',
  'leaf-01',
  'car-01',
  'bicycle-01',
  'motorbike-01',
  'scooter-01',
  'truck',
  'bus-01',
  'taxi-02',
  'train-01',
  'metro',
  'boat',
  'airplane-01',
  'helicopter',
  'parking-meter',
  'ev-charging',
  'fuel-01',
  'petrol-pump',
  'heart-check',
  'pulse-01',
  'stethoscope-02',
  'medicine-01',
  'hospital-01',
  'doctor-01',
  'dental-tooth',
  'bandage',
  'first-aid-kit',
  'vaccine',
  'pill',
  'hair-dryer',
  'perfume',
  'glasses',
  'sunglasses',
  'book-01',
  'school-01',
  'graduation-scroll',
  'football',
  'basketball-01',
  'tennis-ball',
  'volleyball',
  'yoga-01',
  'workout-run',
  'running-shoes',
  'swimming-cap',
  'surfboard',
  'dumbbell-01',
  'game-controller-01',
  'music-note-01',
  'film-01',
  'camera-01',
  'party',
  'theater',
  'ticket-01',
  'popcorn',
  'dice',
  'headphones',
  'mic-01',
  'baby-01',
  'baby-bottle',
  'kid',
  'toy-brick',
  'school-bus',
  'backpack-01',
  'bird',
  'bone-01',
  'smart-phone-01',
  'internet',
  'computer',
  'hotel-01',
  'briefcase-01',
  'job-search',
  'invoice-01',
  'analytics-up',
  'chart-up',
  'trade-up',
  'trade-down',
  'bitcoin',
  'safe-box',
  'atm-01',
  'receipt-text',
  'cashback',
  'profit',
  'tips',
  'taxes',
  'charity',
  'money-bag-01',
  'piggy-bank',
  'cash-01',
  'coin',
  'chart-bar-01',
  'savings',
  'luggage-01',
  'travel-bag',
  'passport-01',
  'tent',
  'compass',
  'map-pin',
  'beach',
  'mountain',
  'camper',
  'globe',
  'campfire',
]
