import {
  Airplane01Icon,
  BankIcon,
  Book01Icon,
  Briefcase01Icon,
  Bus01Icon,
  Car01Icon,
  Cash01Icon,
  ChartBarLineIcon,
  ClothesIcon,
  Coffee01Icon,
  Coins01Icon,
  ComputerIcon,
  CreditCardIcon,
  Dumbbell01Icon,
  Film01Icon,
  Fuel01Icon,
  GameController01Icon,
  GiftIcon,
  GraduationScrollIcon,
  Hamburger01Icon,
  HeartCheckIcon,
  Home01Icon,
  Hospital01Icon,
  Hotel01Icon,
  InternetIcon,
  Invoice01Icon,
  JobSearchIcon,
  Medicine01Icon,
  MoneyBag01Icon,
  MusicNote01Icon,
  PetrolPumpIcon,
  PiggyBankIcon,
  Pizza01Icon,
  Pulse01Icon,
  Restaurant01Icon,
  SavingsIcon,
  School01Icon,
  Shirt01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  Stethoscope02Icon,
  Taxi02Icon,
  Train01Icon,
  Wallet02Icon,
} from '@hugeicons/core-free-icons'
import type { HugeiconsIconProps } from '@hugeicons/react'

type HugeIcon = HugeiconsIconProps['icon']

export const ICON_MAP: Record<string, HugeIcon> = {
  'wallet-02': Wallet02Icon,
  bank: BankIcon,
  'credit-card': CreditCardIcon,
  'money-bag-01': MoneyBag01Icon,
  'piggy-bank': PiggyBankIcon,
  'cash-01': Cash01Icon,
  coin: Coins01Icon,
  'chart-bar-01': ChartBarLineIcon,
  savings: SavingsIcon,
  'home-01': Home01Icon,
  'shopping-bag-01': ShoppingBag01Icon,
  'shopping-cart-01': ShoppingCart01Icon,
  'car-01': Car01Icon,
  'airplane-01': Airplane01Icon,
  'restaurant-01': Restaurant01Icon,
  'coffee-01': Coffee01Icon,
  'pizza-01': Pizza01Icon,
  'hamburger-01': Hamburger01Icon,
  'bus-01': Bus01Icon,
  'taxi-02': Taxi02Icon,
  'train-01': Train01Icon,
  'fuel-01': Fuel01Icon,
  'petrol-pump': PetrolPumpIcon,
  'heart-check': HeartCheckIcon,
  'pulse-01': Pulse01Icon,
  'stethoscope-02': Stethoscope02Icon,
  'medicine-01': Medicine01Icon,
  'hospital-01': Hospital01Icon,
  'book-01': Book01Icon,
  'school-01': School01Icon,
  'graduation-scroll': GraduationScrollIcon,
  'game-controller-01': GameController01Icon,
  'music-note-01': MusicNote01Icon,
  'film-01': Film01Icon,
  'dumbbell-01': Dumbbell01Icon,
  'smart-phone-01': SmartPhone01Icon,
  internet: InternetIcon,
  clothes: ClothesIcon,
  'shirt-01': Shirt01Icon,
  gift: GiftIcon,
  'hotel-01': Hotel01Icon,
  'briefcase-01': Briefcase01Icon,
  'job-search': JobSearchIcon,
  'invoice-01': Invoice01Icon,
  computer: ComputerIcon,
}

export const getIconByName = (name: string): HugeIcon =>
  ICON_MAP[name] ?? Wallet02Icon

export const ACCOUNT_ICON_NAMES = [
  'wallet-02',
  'bank',
  'credit-card',
  'money-bag-01',
  'piggy-bank',
  'cash-01',
  'coin',
  'chart-bar-01',
  'savings',
]

export const CATEGORY_ICON_NAMES = [
  'restaurant-01',
  'coffee-01',
  'pizza-01',
  'hamburger-01',
  'shopping-cart-01',
  'shopping-bag-01',
  'clothes',
  'shirt-01',
  'gift',
  'home-01',
  'car-01',
  'bus-01',
  'taxi-02',
  'train-01',
  'airplane-01',
  'fuel-01',
  'petrol-pump',
  'heart-check',
  'pulse-01',
  'stethoscope-02',
  'medicine-01',
  'hospital-01',
  'book-01',
  'school-01',
  'graduation-scroll',
  'game-controller-01',
  'music-note-01',
  'film-01',
  'dumbbell-01',
  'smart-phone-01',
  'internet',
  'hotel-01',
  'briefcase-01',
  'job-search',
  'invoice-01',
  'computer',
  'money-bag-01',
  'piggy-bank',
  'cash-01',
  'coin',
  'chart-bar-01',
  'savings',
]
